### PR TITLE
Remove leading zero's of an amount

### PR DESCRIPTION
**Pull request by nssnl**
See #122

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Before creating this PR, did you look for a bug/explanation  in upstream project https://github.com/moneyphp/money ?

It sounds likely that they have stumbled upon this already and/or they might appreciate your patch ...

**Comment by nssnl** [comment]
According the documentation, it seems leading zero’s are not supported. See: https://www.moneyphp.org/en/stable/getting-started.html#accepted-integer-values

**Comment by frederikbosch** [comment]
But I think I would willing to merge a PR in DecimalMoneyParser @ moneyphp/money that removes the leading zero's

**Comment by nssnl** [comment]
Allright, makes sense!
Do you want me to create a PR? I’m happy to propose a fix, but there are many ways to remove them, not sure if I can oversee the implications in this other library I’m not familiar with.

**Comment by frederikbosch** [comment]
Just created [PR 702](https://github.com/moneyphp/money/pull/702) that realizes this. I'll give it a week to see if anyone has anything to say about it, otherwise I'll merge it in. Please notify me if I forget, which is perfectly possible. Thanks for your effort here!

**Comment by PowerKiKi** [comment]
Will be fixed via https://github.com/moneyphp/money/pull/702

**Pull request closed without merging**
