### PR TITLE
Add group header additional information

### PR DESCRIPTION
**Pull request by Einenlum**

### CODE REVIEW

**Comment by frederikbosch** [comment]
@Einenlum Just granted you direct access to the repo. Thanks a lot for enhancing this repository!

**Comment by Einenlum** [comment]
@frederikbosch Thanks a lot! Anyway, I think I won't (unless it's really urgent) merge my own PRs (it's always nice to have a review on your work, especially when it's open source) ;).

**Comment by frederikbosch** [comment]
@Einenlum I know it's great to have someone review your work. But to be truely honesty: I just press the merge button. The other side of open source that people have to have time to work on something, either by reviewing or coding. It feels much better being with more than one person!

So please, go ahead and push to master. It is version `0.2.0` that we are working in. The only thing that we should keep in mind in semantic versioning. I don't know your plans, but we might be up to version `0.3.0`.

My plan is to finish my work on [`Money`](https://github.com/moneyphp/money) any time soon and then with version `3.1.0` of Money that includes `PreciseMoney` release `1.0.0` of this package. That is kind of the roadmap I had in mind. In the meantime we could add features of the CAMT standards.

**Comment by Einenlum** [comment]
Thanks for your precisions. Then I'll merge my own PRs (I never push to master directly).
No problem for semver. Upgrading the minor version seems a good idea (the changes have been more than patches).

**Pull request merged**
