### PR TITLE
Added support for structured messages

### PR DESCRIPTION
**Pull request by jonaswouters**

### CODE REVIEW

**Comment by frederikbosch** [comment]
Looks great. Could you add add a test for it?

**Comment by jonaswouters** [comment]
I will after lunch.

**Comment by frederikbosch** [comment]
:+1:

**Comment by jonaswouters** [comment]
Updated

**Comment by jonaswouters** [comment]
Perhaps a tag? :+1:

**Comment by frederikbosch** [comment]
Will do, was distracted after merging. Will tag asap.

**Comment by jonaswouters** [comment]
@frederikbosch ping

**Comment by frederikbosch** [comment]
Done.

**Pull request merged**
