### PR TITLE
Some new features and fixes

### PR DESCRIPTION
**Pull request by tormit**
- Account owner info and servicer info support
- Transaction details related party id and type
- CAMT 052.v1 TxDtls fix
- Test files updates

Ignore other commits. They were temporary and reverted.

### CODE REVIEW

**Comment by tormit** [comment]
Can somebody help with scrutinizer?

**Comment by PowerKiKi** [comment]
It seems there is a lot going on in this PR. It would be best to split it into several dedicated and focused PR, to make it easier to review. Typically you should avoid creating a PR from your master branch, and instead create a topic branch per thing you want to fix/improve.

Also the introduction of Laravel seems overkill to me and the upside is not immediately clear. Not sure I'd merge that.

**Comment by tormit** [comment]
I'm sorry. It's bit chaotic, but I was in hurry to get the necessary fixes and improvements done to implement this library in our software. That why I pushed everything to master in my fork.
Now I just wanted to get my changes up here, so that others can start using them. I also see that my improvements could potentially help to solve some open issues.

It's going to take lot time to split up these things. It's basically starting over again.

Can you review and accept it if I refactor Laravel's data_get() into independent function? I agree that incliding Laravel is overkill, but it was faster way to get tests working.

**Comment by PowerKiKi** [comment]
I won't merge in a single PR. With git cherry-picking, and maybe interactive rebasing, you should be able to easily extract the meaningful commits, and assert that they pass CI independently in their own PR.

Regarding `data_get()`, we don't need a function for that, instead use something like:

```php
$value = $refs->MsgId->foo->bar->baz ?? null;
```

But there is also no point to update every single property access like you did. AFAIK most, if not all, of the code worked without that. Why did you update all of it ?

There are also assignment in if condition and variable named with uppercase letter that won't pass CI. 

IMHO the Laravel commit should not be merged at all. And instead create a new commit with null coalescing operator that update only the few things that really need to be updated.

**Comment by tormit** [comment]
I got errors in tests because of property reference on null object in chained properties.
I review it again.

Well, in general, I'll figure something out about reorganizing commits and changes.

**Pull request closed without merging**
