### PR TITLE
Add camt052 v2 support

### PR DESCRIPTION
**Pull request by Einenlum**
This PR adds Camt052 V4 support.

Other few changes:
* OtherAccount DTO is put under the root DTO namespace (instead of sub Camt053\DTO namespace), since it's also used sometimes by Camt052.
* Misc variables have been added in Address DTO, which are sometimes given in Camt053 and Camt052.

Based on #20. The #20 should be merged first and then this one should be rebased.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@Einenlum Wow! Really a lot of work you put in here! Many thanks for your contributions. I hope you are benefiting a lit from the lib.

Over the weekend I will zoom into your work further. The overall structure looks good. I like the decisions.

Just one thing I noticed quickly. Why did you choose an abstract Record class? I tend to avoid abstract classes mostly. Is there really a shared benefit? Sometimes abstraction is not necessary.

**Comment by Einenlum** [comment]
Thanks for your merges @frederikbosch ! :)

I think you will better understand my choice of an abstract Record class in my next PR ^^. I'm implementing Camt 054 right now. Camt052, 053 and 054 all have a central Record statement in the message, with a different name (Report, Statement and Notification). Report and Statement are quite the same, but Notification never have Balances.

I thought about using a generic Record statement without child class, but I guess it's really possible to realize in the future that there are other differences between the versions. Then it would become a little bit messy IMO.

**Comment by frederikbosch** [comment]
@Einenlum Thanks! I will also spend some hours on the library next week.

**Comment by frederikbosch** [comment]
There is also one thing I would like to do, but that would much more time. To switch from SimpleXML to something like XMLReader in combination with PHP's generator. We found out that CAMT files can become pretty large and that can be troubling to read because it will be read fully into memory.

**Comment by Einenlum** [comment]
That's a nice idea, indeed!

**Pull request merged**
