### PR TITLE
Enhancement: Report code coverage to codecov.io

### LINKED ISSUE #139: Remove scrunitzr
Shall we remove it? I see that test is failing.

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] reports code coverage to [codecov.io](https://codecov.io)

Related to #139.

### CODE REVIEW

**Review by PowerKiKi — CHANGES_REQUESTED** [review]
If @frederikbosch agrees to lose the code quality badge (and all kind of measurement whatsoever), then `.scrutinizer.yml` must be deleted before we can merge this.

**Comment by localheinz** [comment]
@frederikbosch @PowerKiKi 

Note that there are global and repository-specific configuration options: https://docs.codecov.com/docs/codecov-yaml.

**Comment by PowerKiKi** [comment]
Do we need any configuration ?

**Comment by localheinz** [comment]
@PowerKiKi 

Should be fine without a configuration!

**Review by PowerKiKi — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @PowerKiKi!

**Pull request merged**
